import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { CSS3DRenderer, CSS3DObject } from 'three/addons/renderers/CSS3DRenderer.js';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

const $ = s => document.querySelector(s);
const screen = $('#phone-screen'), content = $('#phone-content'), stage = $('#stage');
const state = {locked:false,app:null,volume:50,muted:false,inspect:false,fullscreen:false,wallpaper:0};
const stored = (key, fallback='') => {try{return localStorage.getItem(key)??fallback}catch{return fallback}};
const save = (key,value) => {try{localStorage.setItem(key,value);return true}catch{return false}};
let toastTimer, islandTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function island(message){$('#island').textContent=message;$('#island').classList.add('expanded');clearTimeout(islandTimer);islandTimer=setTimeout(()=>{$('#island').classList.remove('expanded');$('#island').innerHTML='<span></span>'},2600)}
$('#island').onclick=()=>island(state.muted?'Silent mode · Wi-Fi connected':`Volume ${state.volume}% · Wi-Fi connected`);
function time(){const now=new Date();$('#clock').textContent=now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});if($('.lock-time'))$('.lock-time').textContent=$('#clock').textContent}
setInterval(time,1000);time();
const icons={
 Photos:['linear-gradient(135deg,#fff,#e4edf3)','✿'],Camera:['linear-gradient(#e2e7ec,#9daab9)','◎'],Weather:['linear-gradient(#2c93e5,#72cafa)','☀'],Notes:['linear-gradient(#ffdb58 28%,#fff 28%)','≡'],
 Calculator:['linear-gradient(#526272,#243141)','⌗'],Settings:['linear-gradient(#c7d1dc,#758597)','⚙'],Music:['linear-gradient(#ff7394,#ed3f66)','♫'],ChatGPT:['linear-gradient(#32514e,#101e20)','❋'],
 Safari:['linear-gradient(#fcffff,#d3e3ef)','◈'],Phone:['linear-gradient(#74df85,#21af55)','☎'],Messages:['linear-gradient(#79df86,#2ab753)','▰'],Clock:['linear-gradient(#263446,#03090d)','◷']
};
function appButton(name){const [bg,symbol]=icons[name];return `<button class="app-button" data-app="${name}" aria-label="Open ${name}"><span class="app-icon" style="background:${bg};color:${['Camera','Notes','Safari','Photos'].includes(name)?'#344957':'white'}">${symbol}</span><span>${name}</span></button>`}
function bindApps(){content.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>openApp(b.dataset.app))}
function home(){stopAudio();state.app=null;screen.classList.remove('in-app');if(state.locked){renderLock();return}const now=new Date();content.innerHTML=`<div class="home-page"><div class="widgets"><button class="widget" data-app="Weather"><div class="city">Cupertino</div><div class="temp">23°</div><small>☀ Mostly sunny</small><small>H:25° L:16° · Demo</small></button><button class="widget calendar" data-app="Clock"><div class="day">${now.toLocaleDateString('en',{weekday:'long'}).toUpperCase()}</div><div class="date">${now.getDate()}</div><small>Your day, at a glance.</small></button></div><div class="app-grid">${['Photos','Camera','Weather','Notes','Calculator','Settings','Music','ChatGPT'].map(appButton).join('')}</div><div class="pages">● ○</div><div class="dock">${['Phone','Safari','Messages','Clock'].map(appButton).join('')}</div></div>`;bindApps()}
function renderLock(){screen.classList.remove('in-app');content.innerHTML=`<div class="lock"><p>♧</p><div class="lock-date">${new Date().toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric'})}</div><div class="lock-time">${$('#clock').textContent}</div><p>Your virtual world is ready.</p><button id="unlock">Tap to unlock ↑</button></div>`;$('#unlock').onclick=()=>{state.locked=false;home()}}
function lock(){state.locked=!state.locked;home();toast(state.locked?'Phone locked':'Phone unlocked')}
function shell(title,html,cls=''){content.innerHTML=`<div class="app-page ${cls}"><div class="app-nav"><button id="app-back">‹ Home</button><span>${title==='ChatGPT'?'AI · NOT CONNECTED':'VIRTUAL DEVICE'}</span></div>${html}</div>`;$('#app-back').onclick=home}
function openApp(name){stopAudio();if(state.locked)return;state.app=name;screen.classList.add('in-app');
 if(name==='Calculator'){shell(name,'<div class="calc-display" role="status">0</div><div class="calc-grid"></div>','calc');initCalculator();return}
 if(name==='Notes'){shell(name,'<h2>Notes</h2><p id="save-status">Saved on this device</p><textarea class="notes-area" aria-label="Your note" placeholder="A thought for day one…"></textarea>');$('.notes-area').value=stored('iphone-note');$('.notes-area').oninput=e=>{$('#save-status').textContent=save('iphone-note',e.target.value)?'Saved on this device':'Storage unavailable — keep this page open'};return}
 if(name==='Settings'){shell(name,`<h2>Settings</h2><div class="card"><strong>Virtual iPhone</strong><br>Silver titanium · Day 01 concept</div><div class="card"><label class="setting">Wi-Fi <input type="checkbox" checked id="wifi"></label><label class="setting">Dim display <input type="checkbox" id="dim" ${screen.classList.contains('dimmed')?'checked':''}></label><label class="setting">Silent mode <input type="checkbox" id="silent" ${state.muted?'checked':''}></label></div><h3>Wallpaper</h3><div class="wallpapers">${[0,1,2,3].map(i=>`<button class="art-${i}" aria-label="Wallpaper ${i+1}" data-wallpaper="${i}"></button>`).join('')}</div><p>Display preferences and notes are stored in this browser. AI integration will be added in a later phase.</p>`);$('#wifi').onchange=e=>island(e.target.checked?'Wi-Fi enabled · simulated':'Wi-Fi disabled · simulated');$('#dim').onchange=e=>screen.classList.toggle('dimmed',e.target.checked);$('#silent').onchange=toggleMute;content.querySelectorAll('[data-wallpaper]').forEach(b=>b.onclick=()=>{state.wallpaper=+b.dataset.wallpaper;applyWallpaper();save('iphone-wallpaper',state.wallpaper);island('Wallpaper updated')});return}
 if(name==='Photos'){shell(name,`<h2>Photos</h2><p>Wallpaper studies · 4 images</p><div class="photo-grid">${[0,1,2,3].map(i=>`<button class="art-${i}" data-photo="${i}" aria-label="View wallpaper ${i+1}"></button>`).join('')}</div><p>Procedural color studies for your virtual screen.</p>`);content.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{const i=+b.dataset.photo;shell(name,`<h2>Color study ${i+1}</h2><div class="photo-large art-${i}"></div><button id="set-wall" class="primary">Use as wallpaper</button><button id="photos-back" class="primary" style="margin-top:8px">Back to photos</button>`);$('#set-wall').onclick=()=>{state.wallpaper=i;applyWallpaper();save('iphone-wallpaper',i);home();island('Wallpaper updated')};$('#photos-back').onclick=()=>openApp('Photos')});return}
 if(name==='Weather'){shell(name,'<h2>Cupertino</h2><div class="weather-temp">23°</div><div>☀ Mostly sunny</div><p>H:25° L:16°</p><div class="card">A little sunshine for your day.<hr><div class="weather-hours"><span>Now<br>☀<br>23°</span><span>14:00<br>☀<br>24°</span><span>15:00<br>☀<br>25°</span><span>16:00<br>☁<br>24°</span></div></div><p>Demo forecast · not live weather data</p>','weather-page');return}
 if(name==='ChatGPT'){shell(name,'<div class="chat-placeholder"><div class="chat-logo">❋</div><h3>A place for your AI.</h3><p>The screen is ready. Live conversation will be connected when the API is added.</p><div class="card">Day 01 · hardware & interaction<br>Next · your connected assistant</div></div><input type="text" placeholder="AI connection coming next" aria-label="AI connection not yet configured" disabled>');return}
 if(name==='Safari'){shell(name,'<h2>Safari</h2><p>Open a website in a new browser tab.</p><form id="browser-form"><input type="text" id="address" aria-label="Website address" placeholder="example.com" required><button class="primary" style="margin-top:12px">Open website ↗</button></form><div class="card">Websites open outside the virtual phone so their sign-in, security, and navigation work normally.</div>');$('#browser-form').onsubmit=e=>{e.preventDefault();let value=$('#address').value.trim();try{const url=new URL(value.includes('://')?value:'https://'+value);if(!['http:','https:'].includes(url.protocol)||!url.hostname.includes('.'))throw Error();window.open(url.href,'_blank','noopener,noreferrer')}catch{island('Enter a valid website address')}};return}
 if(name==='Music'){shell(name,'<h2>Music</h2><div class="album art-2">♫</div><h3>First Light</h3><p>Studio tone · local audio demo</p><div class="music-controls"><button id="play" aria-label="Play studio tone">▶</button></div><p class="muted">A synthesized ambient chord. Use the volume controls to adjust it.</p>');$('#play').onclick=toggleAudio;return}
 if(name==='Clock'){shell(name,`<h2>Clock</h2><div class="card"><p>LOCAL TIME</p><div id="app-clock" style="font-size:43px">${$('#clock').textContent}</div><p>${Intl.DateTimeFormat().resolvedOptions().timeZone}</p></div>`);return}
 if(name==='Camera'){shell(name,'<h2>Camera</h2><div class="album art-0">◎</div><div class="card">Camera is a visual preview for this concept. Your real camera is not accessed.</div><button class="primary" id="camera-photos">Explore wallpaper studies</button>');$('#camera-photos').onclick=()=>openApp('Photos');return}
 if(name==='Phone'){shell(name,'<h2>Phone</h2><div class="card">This browser concept does not place calls.</div><input type="text" id="dial" aria-label="Phone number" placeholder="Enter a number" inputmode="tel"><div class="calc-grid" style="margin-top:20px">'+['1','2','3','4','5','6','7','8','9','*','0','#'].map(n=>`<button data-digit="${n}">${n}</button>`).join('')+'</div>');content.querySelectorAll('[data-digit]').forEach(b=>b.onclick=()=>{$('#dial').value+=b.dataset.digit});return}
 shell(name,'<h2>Messages</h2><div class="card"><strong>Welcome to Day 01</strong><p>Your virtual phone is ready to explore. Try Calculator, write a note, or rotate the device to see the camera array.</p></div><p>Demo inbox · messaging is not connected.</p>')
}
function initCalculator(){let value='0',previous=null,operator=null,fresh=false;const keys=['AC','±','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','='];$('.calc-grid').innerHTML=keys.map(k=>`<button class="${['÷','×','−','+','='].includes(k)?'op':['AC','±','%'].includes(k)?'utility':k==='0'?'zero':''}" data-key="${k}">${k}</button>`).join('');const compute=()=>{if(previous===null||!operator)return;const a=previous,b=Number(value);value=String(operator==='+'?a+b:operator==='−'?a-b:operator==='×'?a*b:b===0?NaN:a/b);if(!Number.isFinite(Number(value)))value='Error';else value=String(Number(Number(value).toPrecision(10)));previous=null;operator=null};content.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const key=b.dataset.key;if(key==='AC'){value='0';previous=null;operator=null;fresh=false}else if(key==='±'){value=String(-Number(value))}else if(key==='%'){value=String(Number(value)/100)}else if(['+','−','×','÷'].includes(key)){if(!fresh)compute();previous=Number(value);operator=key;fresh=true}else if(key==='='){compute();fresh=true}else{if(fresh||value==='Error'){value='0';fresh=false}if(key==='.'){if(!value.includes('.'))value+='.'}else if(value.length<12)value=value==='0'?key:value+key}$('.calc-display').textContent=value})}
function applyWallpaper(){for(let i=0;i<4;i++)screen.classList.remove('art-'+i);screen.classList.add('art-'+state.wallpaper)}
state.wallpaper=Math.max(0,Math.min(3,Number(stored('iphone-wallpaper','0'))||0));applyWallpaper();
let audioCtx,gain,oscillators=[];
function stopAudio(){oscillators.forEach(o=>o.stop());oscillators=[];if($('#play')){$('#play').textContent='▶';$('#play').setAttribute('aria-label','Play studio tone')}}
async function toggleAudio(){if(oscillators.length){stopAudio();return}try{audioCtx??=new AudioContext();await audioCtx.resume();gain=audioCtx.createGain();gain.gain.value=state.muted?0:state.volume/100*.07;gain.connect(audioCtx.destination);[220,277.18,329.63].forEach(f=>{const o=audioCtx.createOscillator();o.frequency.value=f;o.type='sine';o.connect(gain);o.start();oscillators.push(o)});$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','Pause studio tone');island('♫ First Light · studio tone')}catch{toast('Audio is unavailable in this browser')}}
function volume(delta){state.volume=Math.min(100,Math.max(0,state.volume+delta));$('#volume-value').textContent=`VOL ${state.volume}%`;if(gain)gain.gain.value=state.muted?0:state.volume/100*.07;island(`Volume ${state.volume}%`)}
function toggleMute(){state.muted=!state.muted;$('#mute span').textContent=state.muted?'Silent mode':'Sound on';if(gain)gain.gain.value=state.muted?0:state.volume/100*.07;island(state.muted?'Silent mode enabled':'Sound enabled')}
$('#vol-down').onclick=()=>volume(-10);$('#vol-up').onclick=()=>volume(10);$('#mute').onclick=toggleMute;$('#power').onclick=lock;$('#home').onclick=home;$('#home-indicator').onclick=()=>{if(state.locked)state.locked=false;home()};
let touchStart;screen.addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY}});screen.addEventListener('pointerup',e=>{if(touchStart&&touchStart.y-e.clientY>65&&Math.abs(touchStart.x-e.clientX)<65&&!(e.target instanceof HTMLTextAreaElement)){if(state.locked)state.locked=false;home()}touchStart=null});

// Procedural concept hardware, with a live DOM screen in the same 3D camera space.
const scene=new THREE.Scene(),cssScene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(0,0,13.7);
let renderer;
try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x000000,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('#view').append(renderer.domElement)}catch{toast('3D is unavailable. Opening screen-only view.')}
const cssRenderer=new CSS3DRenderer();$('#screen-host').append(cssRenderer.domElement);
let needsRender=true;
const controls=new OrbitControls(camera,$('#view'));controls.enablePan=false;controls.minDistance=10.5;controls.maxDistance=18.2;controls.enableDamping=true;controls.dampingFactor=.09;controls.rotateSpeed=.6;
const phone=new THREE.Group();scene.add(phone);
const titanium=new THREE.MeshStandardMaterial({color:0xb5bec8,metalness:.94,roughness:.28});const glass=new THREE.MeshPhysicalMaterial({color:0xc0cbd0,metalness:.28,roughness:.2,clearcoat:1});const dark=new THREE.MeshStandardMaterial({color:0x05080c,metalness:.25,roughness:.27});
function box(w,h,d,r,material,x=0,y=0,z=0){let geometry;if(w>2&&h>2){const shape=new THREE.Shape(),l=-w/2,b=-h/2;shape.moveTo(l+r,b);shape.lineTo(l+w-r,b);shape.quadraticCurveTo(l+w,b,l+w,b+r);shape.lineTo(l+w,b+h-r);shape.quadraticCurveTo(l+w,b+h,l+w-r,b+h);shape.lineTo(l+r,b+h);shape.quadraticCurveTo(l,b+h,l,b+h-r);shape.lineTo(l,b+r);shape.quadraticCurveTo(l,b,l+r,b);geometry=new THREE.ExtrudeGeometry(shape,{depth:d-.02,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.01,bevelThickness:.01,curveSegments:16});geometry.translate(0,0,-(d-.02)/2)}else geometry=new RoundedBoxGeometry(w,h,d,5,r);const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);phone.add(mesh);return mesh}
box(3.42,7.06,.34,.48,titanium);box(3.33,6.97,.035,.46,glass,0,0,-.18);box(3.30,6.94,.05,.45,dark,0,0,.18);
const screenObject=new CSS3DObject(screen);screenObject.scale.setScalar(.01);screenObject.position.z=.218;cssScene.add(screenObject);
// Rear quad optics: raised titanium platform, polished rings, and layered blue glass.
box(2.9,2.35,.16,.25,titanium,0,2.14,-.30);
const lensMaterial=new THREE.MeshPhysicalMaterial({color:0x082238,metalness:.65,roughness:.09,clearcoat:1});
function cylinder(radius,depth,material,x,y,z){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,depth,64),material);mesh.rotation.x=Math.PI/2;mesh.position.set(x,y,z);phone.add(mesh);return mesh}
for(const [x,y] of [[-.73,2.70],[.43,2.70],[-.73,1.56],[.43,1.56]]){cylinder(.48,.13,titanium,x,y,-.44);cylinder(.414,.14,dark,x,y,-.48);cylinder(.33,.015,lensMaterial,x,y,-.56);cylinder(.19,.02,dark,x,y,-.571);cylinder(.12,.024,lensMaterial,x-.045,y+.045,-.581)}
cylinder(.15,.04,new THREE.MeshStandardMaterial({color:0xfff1d5,roughness:.3}),1.14,2.6,-.405);cylinder(.085,.045,dark,1.15,1.89,-.41);
const logo=new THREE.Mesh(new THREE.RingGeometry(.23,.245,64),new THREE.MeshStandardMaterial({color:0x718590,metalness:.6,roughness:.3,side:THREE.DoubleSide}));logo.position.set(0,-.15,-.204);phone.add(logo);
const buttons=[];buttons.push({mesh:box(.065,.65,.14,.025,titanium,1.73,1.13,0),action:lock});buttons.push({mesh:box(.065,.48,.14,.025,titanium,-1.73,1.12,0),action:()=>volume(10)});buttons.push({mesh:box(.065,.48,.14,.025,titanium,-1.73,.48,0),action:()=>volume(-10)});buttons.push({mesh:box(.065,.25,.14,.025,titanium,-1.73,1.92,0),action:toggleMute});
box(.55,.024,.115,.02,dark,0,-3.529,0);for(let i=0;i<5;i++){box(.035,.025,.07,.009,dark,.55+i*.13,-3.53,0);box(.035,.025,.07,.009,dark,-.55-i*.13,-3.53,0)}
const seam=new THREE.MeshStandardMaterial({color:0x64727e,metalness:.3,roughness:.6});for(const x of [-1.716,1.716])for(const y of [-2.63,2.96])box(.018,.036,.3,.007,seam,x,y,0);
scene.add(new THREE.HemisphereLight(0xdff2ff,0x334056,3));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(-5,6,6);scene.add(key);const rim=new THREE.DirectionalLight(0x82d4ff,4);rim.position.set(5,1,-5);scene.add(rim);
if(renderer){const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;room.dispose();pmrem.dispose()}
let targetPosition=null;
function face(back=false){targetPosition={theta:back?Math.PI:0,phi:Math.PI/2};if(back)setMode(true)}
function setMode(inspect){state.inspect=inspect;screen.classList.toggle('inspecting',inspect);$('#inspect').classList.toggle('selected',inspect);$('#use').classList.toggle('selected',!inspect);$('#hint').innerHTML=inspect?'Drag the phone to see every angle.<br>Use screen to interact with apps.':'Tap the apps directly on the phone.<br>Drag the background to orbit.';$('#view-label').textContent=inspect?'360° HARDWARE STUDY':'LIVE INTERACTIVE VIEW';if(!inspect&&camera.position.z<5)face(false)}
$('#inspect').onclick=()=>setMode(true);$('#use').onclick=()=>setMode(false);$('#front').onclick=()=>face(false);$('#back').onclick=()=>face(true);$('#zoom').oninput=e=>{targetPosition=null;camera.position.setLength(13.7/(+e.target.value/100));controls.update()};
controls.addEventListener('start',()=>targetPosition=null);controls.addEventListener('change',()=>{needsRender=true;const zoom=Math.round(13.7/camera.position.length()*100);$('#zoom').value=zoom;$('#zoom-value').textContent=zoom+'%'});
const raycaster=new THREE.Raycaster();let down;
$('#view').addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY}});$('#view').addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const rect=stage.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=raycaster.intersectObjects(phone.children)[0];const button=buttons.find(b=>b.mesh===hit?.object);button?.action()});
function fullscreen(on){state.fullscreen=on;document.body.classList.toggle('fullscreen',on);$('#exit-screen').hidden=!on;if(on){stage.append(screen);screen.style.pointerEvents='auto';screen.classList.remove('inspecting');screen.style.visibility='visible'}else{cssRenderer.domElement.firstElementChild.append(screen);screen.style.pointerEvents='';screen.classList.toggle('inspecting',state.inspect)}resize()}
$('#fullscreen').onclick=()=>fullscreen(true);$('#exit-screen').onclick=()=>fullscreen(false);
function resize(){needsRender=true;if(state.fullscreen){document.documentElement.style.setProperty('--screen-scale',Math.min((innerHeight-100)/680,(innerWidth-30)/320));return}const {width,height}=stage.getBoundingClientRect();camera.aspect=width/height;camera.updateProjectionMatrix();renderer?.setSize(width,height);cssRenderer.setSize(width,height)}
new ResizeObserver(resize).observe(stage);window.addEventListener('resize',resize);resize();
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='Escape'){if(state.fullscreen)fullscreen(false);else home()}if(e.key==='1')face(false);if(e.key==='2')face(true);if(e.key.toLowerCase()==='l')lock();if(e.key.toLowerCase()==='h')home()});
function animate(){requestAnimationFrame(animate);if(targetPosition){const theta=controls.getAzimuthalAngle(),phi=controls.getPolarAngle();const delta=Math.atan2(Math.sin(targetPosition.theta-theta),Math.cos(targetPosition.theta-theta));camera.position.setFromSphericalCoords(camera.position.length(),phi+(targetPosition.phi-phi)*.12,theta+delta*.12);if(Math.abs(delta)+Math.abs(targetPosition.phi-phi)<.001)targetPosition=null}controls.update();if(!state.fullscreen&&needsRender){screen.style.visibility=camera.position.z>.25?'visible':'hidden';renderer?.render(scene,camera);cssRenderer.render(cssScene,camera);needsRender=false}if($('#app-clock'))$('#app-clock').textContent=$('#clock').textContent}
home();animate();if(!renderer)fullscreen(true);
