import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(15000);
try {
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto(process.env.DEMO_URL||'http://127.0.0.1:5180');
await page.getByRole('button',{name:'Open Calculator',exact:true}).click();
for(const name of ['7','×','8','='])await page.getByRole('button',{name,exact:true}).click();
assert.equal(await page.locator('.calc-display').textContent(),'56');
for(const name of ['AC','1','÷','0','='])await page.getByRole('button',{name,exact:true}).click();
assert.equal(await page.locator('.calc-display').textContent(),'Error');
await page.getByRole('button',{name:'Go home',exact:true}).click();
await page.getByRole('button',{name:'Open Notes',exact:true}).click();
await page.getByRole('textbox',{name:'Your note'}).fill('Day 01 — persistence check.');
await page.reload();
await page.getByRole('button',{name:'Open Notes',exact:true}).click();
assert.equal(await page.getByRole('textbox',{name:'Your note'}).inputValue(),'Day 01 — persistence check.');
await page.getByRole('button',{name:'Go home',exact:true}).click();
await page.locator('#power').click();
await page.getByRole('button',{name:'Tap to unlock ↑'}).click();
await page.getByRole('button',{name:'Open Settings',exact:true}).click();
await page.getByRole('button',{name:'Wallpaper 3',exact:true}).click();
await page.getByRole('checkbox',{name:'Dim display'}).check();
assert.match(await page.locator('#phone-screen').getAttribute('class'),/dimmed/);
await page.getByRole('checkbox',{name:'Dim display'}).uncheck();
await page.locator('#home').click();
await page.locator('#fullscreen').click();
await page.getByRole('button',{name:'Open Calculator',exact:true}).click();
await page.getByRole('button',{name:'9',exact:true}).click();
assert.equal(await page.locator('.calc-display').textContent(),'9');
await page.locator('#exit-screen').click();
await page.locator('#home').click();
await page.locator('#back').click();
await page.waitForFunction(()=>getComputedStyle(document.querySelector('#phone-screen')).visibility==='hidden');
await page.waitForTimeout(1800);
await page.screenshot({path:'back-check.png',fullPage:true});
await page.locator('#use').click();
await page.waitForFunction(()=>getComputedStyle(document.querySelector('#phone-screen')).visibility==='visible');
await page.waitForTimeout(1800);
await page.getByRole('button',{name:'Open ChatGPT',exact:true}).click();
assert(await page.getByRole('textbox',{name:'AI connection not yet configured'}).isDisabled());
await page.locator('#home').click();
await page.screenshot({path:'desktop-check.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(500);
await page.screenshot({path:'mobile-check.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.getByRole('button',{name:'Open Calculator',exact:true}).click();
await page.getByRole('button',{name:'3',exact:true}).click();
await page.getByRole('button',{name:'+',exact:true}).click();
await page.getByRole('button',{name:'2',exact:true}).click();
await page.getByRole('button',{name:'=',exact:true}).click();
assert.equal(await page.locator('.calc-display').textContent(),'5');
assert.deepEqual(errors,[]);
console.log('PASS: arithmetic, zero-division, notes persistence, lock/unlock, settings, screen-only interaction, return to 3D, back/front visibility, disconnected AI, mobile layout and mobile calculator; no page errors.');
} finally { await browser.close(); }
